version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: lab_postgres
    environment:
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_pass
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
    volumes:
      - .:/lab
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
